runtime: nodejs20

handlers:
  # Serve static assets
  - url: /assets
    static_dir: dist/assets

  # Serve other static files
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/.*\..+$

  # Handle all other routes and serve the index.html file
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
